SELECT /*+ NOPARALLEL MONITORING */
    A.DEVICE_NAME,
    B.PRIMARY_LOCATION,
    AVG(B.MEASUREMENT_VALUE) AS AVG_MEASUREMENT_VALUE
FROM P_8K_800X_NOCOMPRESS_LARGE A
    INNER JOIN C_8K_800X_NOCOMPRESS_LARGE B
        ON A.PARENT_KEY = B.PARENT_KEY
GROUP BY
    A.DEVICE_NAME,
    B.PRIMARY_LOCATION;

SELECT /*+ NOPARALLEL MONITORING */
    DEVICE_NAME,
    PRIMARY_LOCATION,
    AVG(MEASUREMENT_VALUE) AS AVG_MEASUREMENT_VALUE
FROM PC_8K_800X_SORT_LARGE
GROUP BY
    DEVICE_NAME,
    PRIMARY_LOCATION;

SELECT /*+ NOPARALLEL MONITORING */
    B.DEVICE_NAME,
    C.PRIMARY_LOCATION,
    AVG(A.MEASUREMENT_VALUE) AS AVG_MEASUREMENT_VALUE
FROM PC_8K_800X_SORT_NORM_LARGE A
    INNER JOIN DEVICE_NAME_REF_LARGE B
        ON A.DEVICE_NAME_KEY = B.DEVICE_NAME_KEY
    INNER JOIN PRIMARY_LOCATION_REF_LARGE C
        ON A.PRIMARY_LOCATION_KEY = C.PRIMARY_LOCATION_KEY
GROUP BY
    B.DEVICE_NAME,
    C.PRIMARY_LOCATION;
	