DROP TABLE T1_BASE;
CREATE TABLE T1_BASE

(
DEVICE_KEY NUMBER,
DEVICE_LOCAL_TIME TIMESTAMP(6),
SENSOR_OUTPUT NUMBER
)
PCTFREE 2
INITRANS 1 
MAXTRANS 255
NOCOMPRESS
TABLESPACE CAP_8K;


BEGIN

FOR A IN 1..8 LOOP

INSERT INTO T1_BASE

SELECT
    A AS DEVICE_ID,
    TO_TIMESTAMP('20170101 00:00:00.000', 'yyyymmdd hh24:mi:ss.ff') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 364),'DAY') AS DEVICE_LOCAL_TIME,
    ROUND(DBMS_RANDOM.VALUE(1001, 1999)) AS SENSOR_OUTPUT
FROM DUAL
CONNECT BY LEVEL <= 1000000/8;

END LOOP;

COMMIT;

DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'KIRBYS', TABNAME => 'T1_BASE', GRANULARITY => 'ALL', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, DEGREE => 16, CASCADE => DBMS_STATS.AUTO_CASCADE);

END;
/

SELECT
    A.*,
    DBMS_ROWID.ROWID_TO_ABSOLUTE_FNO(ROWID,'KIRBYS', 'BLOCK_DUMP_TEST_NOCOMPRESS') AS ABSOLUTE_FNO,
    DBMS_ROWID.ROWID_BLOCK_NUMBER(ROWID) AS BLOCK_NUM
FROM KIRBYS.BLOCK_DUMP_TEST_NOCOMPRESS A;

CREATE TABLE T1_NOCOMPRESS_8K
NOCOMPRESS
TABLESPACE CAP_8K
PCTFREE 0

AS SELECT * FROM T1_BASE;

CREATE TABLE T1_NOCOMPRESS_16K
NOCOMPRESS
TABLESPACE CAP_16K
PCTFREE 0

AS SELECT * FROM T1_BASE;

CREATE TABLE T1_NOCOMPRESS_32K
NOCOMPRESS
TABLESPACE CAP_32K
PCTFREE 0

AS SELECT * FROM T1_BASE;

CREATE TABLE T1_BASIC_8K
COMPRESS BASIC
TABLESPACE CAP_8K
PCTFREE 0

AS SELECT * FROM T1_BASE;

CREATE TABLE T1_BASIC_16K
COMPRESS BASIC
TABLESPACE CAP_16K
PCTFREE 0

AS SELECT * FROM T1_BASE;

CREATE TABLE T1_BASIC_32K
COMPRESS BASIC
TABLESPACE CAP_32K
PCTFREE 0

AS SELECT * FROM T1_BASE;

CREATE TABLE T1_BASIC_8K_ORDERED_1
COMPRESS BASIC
TABLESPACE CAP_8K
PCTFREE 0

AS SELECT * FROM T1_BASE
ORDER BY
    DEVICE_KEY;

CREATE TABLE T1_BASIC_16K_ORDERED_1
COMPRESS BASIC
TABLESPACE CAP_16K
PCTFREE 0

AS SELECT * FROM T1_BASE
ORDER BY
    DEVICE_KEY;

CREATE TABLE T1_BASIC_32K_ORDERED_1
COMPRESS BASIC
TABLESPACE CAP_32K
PCTFREE 0

AS SELECT * FROM T1_BASE
ORDER BY
    DEVICE_KEY;

CREATE TABLE T1_BASIC_8K_ORDERED_13
COMPRESS BASIC
TABLESPACE CAP_8K
PCTFREE 0

AS SELECT * FROM T1_BASE
ORDER BY
    DEVICE_KEY,
    SENSOR_OUTPUT;
    
CREATE TABLE T1_BASIC_16K_ORDERED_13
COMPRESS BASIC
TABLESPACE CAP_16K
PCTFREE 0

AS SELECT * FROM T1_BASE
ORDER BY
    DEVICE_KEY,
    SENSOR_OUTPUT;
    
CREATE TABLE T1_BASIC_32K_ORDERED_13
COMPRESS BASIC
TABLESPACE CAP_32K
PCTFREE 0

AS SELECT * FROM T1_BASE
ORDER BY
    DEVICE_KEY,
    SENSOR_OUTPUT;
    
SELECT
    A.COMPRESS_FOR,
    A.OWNER,
    A.TABLE_NAME,
    A.TABLESPACE_NAME,
    A.NUM_ROWS,
    B.BLOCK_SIZE,
    A.BLOCKS,
    B.BLOCK_SIZE * A.BLOCKS / POWER(1024,2) AS TABLE_SIZE_MB
FROM DBA_TABLES A
    INNER JOIN DBA_TABLESPACES B
        ON A.TABLESPACE_NAME = B.TABLESPACE_NAME
--WHERE A.TABLE_NAME IN('T1_BASE','T1_NOCOMPRESS_8K','T1_NOCOMPRESS_16K','T1_NOCOMPRESS_32K','T1_BASIC_8K','T1_BASIC_16K','T1_BASIC_32K')
WHERE B.TABLESPACE_NAME IN ('CAP_8K','CAP_16K','CAP_32K')
ORDER BY
    TABLE_SIZE_MB;
