DROP TABLE T1_BASE;
CREATE TABLE CAPSTONE.T1_BASE

(
DEVICE_KEY NUMBER,
DEVICE_LOCAL_TIME TIMESTAMP(6),
SENSOR_OUTPUT NUMBER
)
PCTFREE 0
INITRANS 1 
MAXTRANS 255
NOCOMPRESS
TABLESPACE CAP8K;


BEGIN

FOR A IN 1..8 LOOP

INSERT INTO CAPSTONE.T1_BASE

SELECT
    A AS DEVICE_ID,
    TO_TIMESTAMP('20170101 00:00:00.000', 'yyyymmdd hh24:mi:ss.ff') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 364),'DAY') AS DEVICE_LOCAL_TIME,
    ROUND(DBMS_RANDOM.VALUE(1001, 1999)) AS SENSOR_OUTPUT
FROM DUAL
CONNECT BY LEVEL <= 1000000/8;

END LOOP;

COMMIT;

DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'CAPSTONE', TABNAME => 'T1_BASE', GRANULARITY => 'ALL', ESTIMATE_PERCENT => DBMS_STATS.AUTO_SAMPLE_SIZE, DEGREE => 16, CASCADE => DBMS_STATS.AUTO_CASCADE);

END;
/

CREATE TABLE CAPSTONE.T1_16K_BASIC COMPRESS BASIC PCTFREE 0 TABLESPACE CAP16K STORAGE(INITIAL 16384) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_16K_NOCOMPRESS NOCOMPRESS PCTFREE 0 TABLESPACE CAP16K STORAGE(INITIAL 16384) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_16K_ADVANCED ROW STORE COMPRESS ADVANCED PCTFREE 0 TABLESPACE CAP16K STORAGE(INITIAL 16384) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_32K_BASIC COMPRESS BASIC PCTFREE 0 TABLESPACE CAP32K STORAGE(INITIAL 32768) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_32K_NOCOMPRESS NOCOMPRESS PCTFREE 0 TABLESPACE CAP32K STORAGE(INITIAL 32768) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_32K_ADVANCED ROW STORE COMPRESS ADVANCED PCTFREE 0 TABLESPACE CAP32K STORAGE(INITIAL 32768) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_8K_BASIC COMPRESS BASIC PCTFREE 0 TABLESPACE CAP8K STORAGE(INITIAL 8192) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_8K_NOCOMPRESS NOCOMPRESS PCTFREE 0 TABLESPACE CAP8K STORAGE(INITIAL 8192) AS SELECT * FROM CAPSTONE.T1_BASE;
CREATE TABLE CAPSTONE.T1_8K_ADVANCED ROW STORE COMPRESS ADVANCED PCTFREE 0 TABLESPACE CAP8K STORAGE(INITIAL 8192) AS SELECT * FROM CAPSTONE.T1_BASE;
    
SELECT
    A.COMPRESS_FOR,
    A.OWNER,
    A.TABLE_NAME,
    A.TABLESPACE_NAME,
    A.INITIAL_EXTENT,
    A.NEXT_EXTENT,
    A.NUM_ROWS,
    B.BLOCK_SIZE/POWER(1024,1) || 'k' AS BLOCK_SIZE,
    A.BLOCKS,
    B.BLOCK_SIZE * A.BLOCKS / POWER(1024,2) AS TABLE_SIZE_MB
FROM DBA_TABLES A
    INNER JOIN DBA_TABLESPACES B
        ON A.TABLESPACE_NAME = B.TABLESPACE_NAME
WHERE B.TABLESPACE_NAME IN ('CAP8K','CAP16K','CAP32K')
ORDER BY
    TABLE_SIZE_MB;

SELECT * FROM DBA_EXTENTS
WHERE TABLESPACE_NAME = 'CAP8K';
