ALTER SESSION SET WORKAREA_SIZE_POLICY = MANUAL;
ALTER SESSION SET SORT_AREA_SIZE = 2147483647; --1 Byte short of 2GB
ALTER SESSION SET HASH_AREA_SIZE = 2147483647; --1 Byte short of 2GB
/

BEGIN
    DBMS_APPLICATION_INFO.SET_MODULE('CAPSTONE','IO_CPU_TEST'); 
END;
/
SELECT * FROM V$ACTIVE_SESSION_HISTORY WHERE MODULE = 'CAPSTONE' AND SQL_OPNAME = 'SELECT' ORDER BY SAMPLE_TIME DESC;
SELECT * FROM V$SESSION WHERE CLIENT_INFO = 'IO_CPU_TEST';
SELECT * FROM V$PROCESS;
SELECT * FROM V$SESSTAT;


ALTER SYSTEM FLUSH BUFFER_CACHE GLOBAL;
ALTER SYSTEM FLUSH BUFFER_POOL ALL;
ALTER SYSTEM FLUSH FLASH_CACHE GLOBAL;
ALTER SYSTEM FLUSH SHARED_POOL;


SELECT /*+ NOPARALLEL MONITORING */
    A.DEVICE_NAME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    AVG(B.MEASUREMENT_VALUE) AS AVG_MEASUREMENT_VALUE
FROM CAPSTONE.P_32K_800X_SORT A
    INNER JOIN CAPSTONE.C_32K_800X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
GROUP BY
    A.DEVICE_NAME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION;