TRUNCATE TABLE CAPSTONE.PARENT_TABLE_TEST;
DROP TABLE CAPSTONE.PARENT_TABLE_TEST;
CREATE TABLE CAPSTONE.PARENT_TABLE_TEST

(
PARENT_KEY NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1000000,
DEVICE_NAME VARCHAR(16),
MEASUREMENT_TIME TIMESTAMP(6)
);

TRUNCATE TABLE CAPSTONE.CHILD_TABLE_TEST;
DROP TABLE CAPSTONE.CHILD_TABLE_TEST;
CREATE TABLE CAPSTONE.CHILD_TABLE_TEST

(
PARENT_KEY NUMBER,
PRIMARY_LOCATION VARCHAR(16),
SECONDARY_LOCATION VARCHAR(16),
MEASUREMENT_VALUE NUMBER
);

BEGIN

FOR A IN 10..19 LOOP

INSERT INTO CAPSTONE.PARENT_TABLE_TEST

(
DEVICE_NAME,
MEASUREMENT_TIME
)

SELECT
--    A*ROWNUM AS PARENT_KEY,
    'DEVICE_NUMBER_'||A AS DEVICE_NAME,
    TO_DATE(20170101, 'yyyymmdd') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 31500000), 'second') AS MEASUREMENT_TIME
FROM DUAL
CONNECT BY LEVEL <= 100000;

COMMIT;

END LOOP;

END;
/
SELECT * FROM CAPSTONE.PARENT_TABLE_TEST;

SELECT
    MEASUREMENT_TIME,
    COUNT(*)
FROM CAPSTONE.PARENT_TABLE_TEST
GROUP BY
    MEASUREMENT_TIME
HAVING COUNT(*) >1;


BEGIN

FOR A IN 1..2 LOOP
FOR B IN 1..5 LOOP

INSERT INTO CAPSTONE.CHILD_TABLE_TEST

SELECT
    PARENT_KEY,
    'PRIMARY_LOCN_00' || A AS PRIMARY_LOCATION,
    'SECONDARY_LOCN_' || B AS SECONDARY_LOCATION,
    ROUND(DBMS_RANDOM.VALUE(10000000, 20000000),0) AS MEASUREMENT_VALUE
FROM CAPSTONE.PARENT_TABLE_TEST
--WHERE DEVICE_NAME = 'DEVICE_NUMBER_10';

COMMIT;

END LOOP;
END LOOP;

END;
/
SELECT * FROM CAPSTONE.CHILD_TABLE_TEST;

SELECT
    MEASUREMENT_VALUE,
    COUNT(*)
FROM CAPSTONE.CHILD_TABLE_TEST
GROUP BY
    MEASUREMENT_VALUE
ORDER BY
    COUNT(*) DESC;
    
CREATE TABLE CAPSTONE.P_8K_NOCOMPRESS PCTFREE 0 NOCOMPRESS TABLESPACE CAP8K AS SELECT * FROM CAPSTONE.PARENT_TABLE_TEST;
CREATE TABLE CAPSTONE.C_8K_NOCOMPRESS PCTFREE 0 NOCOMPRESS TABLESPACE CAP8K AS SELECT * FROM CAPSTONE.CHILD_TABLE_TEST;

CREATE TABLE CAPSTONE.P_8K_COMP_RAND PCTFREE 0 COMPRESS BASIC TABLESPACE CAP8K AS SELECT * FROM CAPSTONE.PARENT_TABLE_TEST ORDER BY MEASUREMENT_TIME, PARENT_KEY, DEVICE_NAME;
CREATE TABLE CAPSTONE.C_8K_COMP_RAND PCTFREE 0 COMPRESS BASIC TABLESPACE CAP8K AS SELECT * FROM CAPSTONE.CHILD_TABLE_TEST ORDER BY MEASUREMENT_VALUE, PARENT_KEY, SECONDARY_LOCATION, PRIMARY_LOCATION;

CREATE TABLE CAPSTONE.P_8K_COMP_SORT PCTFREE 0 COMPRESS BASIC TABLESPACE CAP8K AS SELECT * FROM CAPSTONE.PARENT_TABLE_TEST ORDER BY DEVICE_NAME, MEASUREMENT_TIME, PARENT_KEY;
CREATE TABLE CAPSTONE.C_8K_COMP_SORT PCTFREE 0 COMPRESS BASIC TABLESPACE CAP8K AS SELECT * FROM CAPSTONE.CHILD_TABLE_TEST ORDER BY PRIMARY_LOCATION,SECONDARY_LOCATION,PARENT_KEY,MEASUREMENT_VALUE;