/*
Some queries for debugging
*/

SELECT
    PARENT_CHILD_RATIO,
    COUNT(*) AS TOTAL_ROWS
FROM CAPSTONE.PARENT_TABLE_TEST
GROUP BY
    PARENT_CHILD_RATIO
ORDER BY
    TOTAL_ROWS DESC;

SELECT
    PARENT_CHILD_RATIO,
    COUNT(*) AS TOTAL_ROWS
FROM CAPSTONE.CHILD_TABLE_TEST
GROUP BY
    PARENT_CHILD_RATIO
ORDER BY 
    TOTAL_ROWS;

SELECT --Making sure there are no dupes for MEASUREMENT_VALUE
    RANDOM_VALUE,
    COUNT(*)
FROM CAPSTONE.CHILD_TABLE_TEST
GROUP BY
    RANDOM_VALUE
ORDER BY
    COUNT(*) DESC;

/*
You should be able to start from here and highlight to the bottom and hit go.  You must create the reference tables first, however.

    1)  Create the Parent test table that can be used to create other tables using CTAS
    2)  Insert into the Parent test table to enable all different experiments
    3)  Create the Child test table to be used later for CTAS
    4)  Insert into the Child test table to enable all different experiments
    4)  Create a bunch of tables...
*/

--TRUNCATE TABLE CAPSTONE.PARENT_TABLE_TEST;
DROP TABLE CAPSTONE.PARENT_TABLE_TEST;
CREATE TABLE CAPSTONE.PARENT_TABLE_TEST

(
PARENT_CHILD_RATIO VARCHAR2(16),
PARENT_KEY NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1000000000, --want to create a key that is at least 1B rows to match the typical length for our big tables
DEVICE_NAME VARCHAR(16),
MEASUREMENT_TIME TIMESTAMP(6)
)
NOLOGGING;


/*
Inserting into a parent table
*/

BEGIN

FOR A IN 10..19 LOOP --To keep the number of digits equal to 2 so my column length is 16 for all rows

INSERT INTO CAPSTONE.PARENT_TABLE_TEST

(
PARENT_CHILD_RATIO,
DEVICE_NAME,
MEASUREMENT_TIME
)

SELECT
    '10X' AS PARENT_CHILD_RATIO,
    'DEVICE_NUMBER_'||A AS DEVICE_NAME,
    TO_DATE(20170101, 'yyyymmdd') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 31500000), 'second') AS MEASUREMENT_TIME
FROM DUAL
CONNECT BY LEVEL <= 10000; --Total of 100k rows with looping 10 times

COMMIT;

INSERT INTO CAPSTONE.PARENT_TABLE_TEST

(
PARENT_CHILD_RATIO,
DEVICE_NAME,
MEASUREMENT_TIME
)

SELECT
    '50X' AS PARENT_CHILD_RATIO,
    'DEVICE_NUMBER_'||A AS DEVICE_NAME,
    TO_DATE(20170101, 'yyyymmdd') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 31500000), 'second') AS MEASUREMENT_TIME
FROM DUAL
CONNECT BY LEVEL <= 2000; --Total of 20k rows with the looping 10 times

COMMIT;

INSERT INTO CAPSTONE.PARENT_TABLE_TEST

(
PARENT_CHILD_RATIO,
DEVICE_NAME,
MEASUREMENT_TIME
)

SELECT
    '200X' AS PARENT_CHILD_RATIO,
    'DEVICE_NUMBER_'||A AS DEVICE_NAME,
    TO_DATE(20170101, 'yyyymmdd') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 31500000), 'second') AS MEASUREMENT_TIME
FROM DUAL
CONNECT BY LEVEL <= 500; --Total of 6250 rows with looping 10 times

COMMIT;

INSERT INTO CAPSTONE.PARENT_TABLE_TEST

(
PARENT_CHILD_RATIO,
DEVICE_NAME,
MEASUREMENT_TIME
)

SELECT
    '400X' AS PARENT_CHILD_RATIO,
    'DEVICE_NUMBER_'||A AS DEVICE_NAME,
    TO_DATE(20170101, 'yyyymmdd') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 31500000), 'second') AS MEASUREMENT_TIME
FROM DUAL
CONNECT BY LEVEL <= 250; --Total of 2500 rows with looping 10 times

COMMIT;

INSERT INTO CAPSTONE.PARENT_TABLE_TEST

(
PARENT_CHILD_RATIO,
DEVICE_NAME,
MEASUREMENT_TIME
)

SELECT
    '800X' AS PARENT_CHILD_RATIO,
    'DEVICE_NUMBER_'||A AS DEVICE_NAME,
    TO_DATE(20170101, 'yyyymmdd') + NUMTODSINTERVAL(DBMS_RANDOM.VALUE(0, 31500000), 'second') AS MEASUREMENT_TIME
FROM DUAL
CONNECT BY LEVEL <= 125; --Total of 1250 rows with looping 10 times

COMMIT;

END LOOP;

END;
/

/*
Creating a child table
*/

--TRUNCATE TABLE CAPSTONE.CHILD_TABLE_TEST;
DROP TABLE CAPSTONE.CHILD_TABLE_TEST;
CREATE TABLE CAPSTONE.CHILD_TABLE_TEST

(
PARENT_CHILD_RATIO VARCHAR(16),
PARENT_KEY NUMBER,
PRIMARY_LOCATION VARCHAR(16),
SECONDARY_LOCATION VARCHAR(16),
MEASUREMENT_VALUE NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1000000000000, --starting with 1E12 digits like our drop count table
RANDOM_VALUE NUMBER
);

/*
Inserting into a child table for a 10 to 1 ratio child/parent.
*/

BEGIN

FOR A IN 10..19 LOOP --Primary Location
FOR B IN 10..10 LOOP --Secondary Location

INSERT INTO CAPSTONE.CHILD_TABLE_TEST

(
PARENT_CHILD_RATIO,
PARENT_KEY,
PRIMARY_LOCATION,
SECONDARY_LOCATION,
RANDOM_VALUE
)

SELECT
    A.PARENT_CHILD_RATIO,
    A.PARENT_KEY,
    'PRIM_LOCN_0000' || A AS PRIMARY_LOCATION,
    'SEC_LOCN_00000' || B AS SECONDARY_LOCATION,
    DBMS_RANDOM.VALUE(0, 100000)
FROM CAPSTONE.PARENT_TABLE_TEST A
WHERE PARENT_CHILD_RATIO = '10X';

COMMIT;

END LOOP;
END LOOP;

FOR A IN 10..19 LOOP --Primary Location
FOR B IN 10..14 LOOP --Secondary Location

INSERT INTO CAPSTONE.CHILD_TABLE_TEST

(
PARENT_CHILD_RATIO,
PARENT_KEY,
PRIMARY_LOCATION,
SECONDARY_LOCATION,
RANDOM_VALUE
)

SELECT
    A.PARENT_CHILD_RATIO,
    A.PARENT_KEY,
    'PRIM_LOCN_0000' || A AS PRIMARY_LOCATION,
    'SEC_LOCN_00000' || B AS SECONDARY_LOCATION,
    DBMS_RANDOM.VALUE(0, 100000)
FROM CAPSTONE.PARENT_TABLE_TEST A
WHERE PARENT_CHILD_RATIO = '50X';

COMMIT;

END LOOP;
END LOOP;

FOR A IN 10..19 LOOP --Primary Location
FOR B IN 10..29 LOOP --Secondary Location

INSERT INTO CAPSTONE.CHILD_TABLE_TEST

(
PARENT_CHILD_RATIO,
PARENT_KEY,
PRIMARY_LOCATION,
SECONDARY_LOCATION,
RANDOM_VALUE
)

SELECT
    A.PARENT_CHILD_RATIO,
    A.PARENT_KEY,
    'PRIM_LOCN_0000' || A AS PRIMARY_LOCATION,
    'SEC_LOCN_00000' || B AS SECONDARY_LOCATION,
    DBMS_RANDOM.VALUE(0, 100000)
FROM CAPSTONE.PARENT_TABLE_TEST A
WHERE PARENT_CHILD_RATIO = '200X';

COMMIT;

END LOOP;
END LOOP;

FOR A IN 10..19 LOOP --Primary Location
FOR B IN 10..49 LOOP --Secondary Location

INSERT INTO CAPSTONE.CHILD_TABLE_TEST

(
PARENT_CHILD_RATIO,
PARENT_KEY,
PRIMARY_LOCATION,
SECONDARY_LOCATION,
RANDOM_VALUE
)

SELECT
    A.PARENT_CHILD_RATIO,
    A.PARENT_KEY,
    'PRIM_LOCN_0000' || A AS PRIMARY_LOCATION,
    'SEC_LOCN_00000' || B AS SECONDARY_LOCATION,
    DBMS_RANDOM.VALUE(0, 100000)
FROM CAPSTONE.PARENT_TABLE_TEST A
WHERE PARENT_CHILD_RATIO = '400X';

COMMIT;

END LOOP;
END LOOP;

FOR A IN 10..19 LOOP --Primary Location
FOR B IN 10..89 LOOP --Secondary Location

INSERT INTO CAPSTONE.CHILD_TABLE_TEST

(
PARENT_CHILD_RATIO,
PARENT_KEY,
PRIMARY_LOCATION,
SECONDARY_LOCATION,
RANDOM_VALUE
)

SELECT
    A.PARENT_CHILD_RATIO,
    A.PARENT_KEY,
    'PRIM_LOCN_0000' || A AS PRIMARY_LOCATION,
    'SEC_LOCN_00000' || B AS SECONDARY_LOCATION,
    DBMS_RANDOM.VALUE(0, 100000)
FROM CAPSTONE.PARENT_TABLE_TEST A
WHERE PARENT_CHILD_RATIO = '800X';

COMMIT;

END LOOP;
END LOOP;

END;
/


    
/*
Creating the tables for the compression ratio test.  

    1)  Combine Parent Child tables into one
    2)  
*/
    
CREATE TABLE CAPSTONE.P_8K_10X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X';

CREATE TABLE CAPSTONE.C_8K_10X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X';

CREATE TABLE CAPSTONE.P_8K_10X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_8K_10X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_8K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_8K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;










CREATE TABLE CAPSTONE.P_8K_50X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X';

CREATE TABLE CAPSTONE.C_8K_50X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X';

CREATE TABLE CAPSTONE.P_8K_50X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_8K_50X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_8K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_8K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;










CREATE TABLE CAPSTONE.P_8K_200X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X';

CREATE TABLE CAPSTONE.C_8K_200X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X';

CREATE TABLE CAPSTONE.P_8K_200X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_8K_200X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_8K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_8K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;









CREATE TABLE CAPSTONE.P_8K_400X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X';

CREATE TABLE CAPSTONE.C_8K_400X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X';

CREATE TABLE CAPSTONE.P_8K_400X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_8K_400X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_8K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_8K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;









CREATE TABLE CAPSTONE.P_8K_800X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X';

CREATE TABLE CAPSTONE.C_8K_800X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X';

CREATE TABLE CAPSTONE.P_8K_800X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_8K_800X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_8K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_8K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;



















CREATE TABLE CAPSTONE.P_16K_10X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X';

CREATE TABLE CAPSTONE.C_16K_10X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X';

CREATE TABLE CAPSTONE.P_16K_10X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_16K_10X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_16K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_16K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;










CREATE TABLE CAPSTONE.P_16K_50X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X';

CREATE TABLE CAPSTONE.C_16K_50X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X';

CREATE TABLE CAPSTONE.P_16K_50X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_16K_50X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_16K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_16K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;










CREATE TABLE CAPSTONE.P_16K_200X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X';

CREATE TABLE CAPSTONE.C_16K_200X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X';

CREATE TABLE CAPSTONE.P_16K_200X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_16K_200X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_16K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_16K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;









CREATE TABLE CAPSTONE.P_16K_400X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X';

CREATE TABLE CAPSTONE.C_16K_400X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X';

CREATE TABLE CAPSTONE.P_16K_400X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_16K_400X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_16K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_16K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;









CREATE TABLE CAPSTONE.P_16K_800X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X';

CREATE TABLE CAPSTONE.C_16K_800X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X';

CREATE TABLE CAPSTONE.P_16K_800X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_16K_800X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_16K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_16K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;



















CREATE TABLE CAPSTONE.P_32K_10X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X';

CREATE TABLE CAPSTONE.C_32K_10X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X';

CREATE TABLE CAPSTONE.P_32K_10X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_32K_10X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_32K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_32K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '10X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;










CREATE TABLE CAPSTONE.P_32K_50X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X';

CREATE TABLE CAPSTONE.C_32K_50X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X';

CREATE TABLE CAPSTONE.P_32K_50X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_32K_50X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_32K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_32K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '50X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;










CREATE TABLE CAPSTONE.P_32K_200X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X';

CREATE TABLE CAPSTONE.C_32K_200X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X';

CREATE TABLE CAPSTONE.P_32K_200X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_32K_200X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_32K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_32K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '200X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;









CREATE TABLE CAPSTONE.P_32K_400X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X';

CREATE TABLE CAPSTONE.C_32K_400X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X';

CREATE TABLE CAPSTONE.P_32K_400X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_32K_400X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_32K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_32K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '400X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;









CREATE TABLE CAPSTONE.P_32K_800X_NOCOMPRESS 
    PCTFREE 0
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X';

CREATE TABLE CAPSTONE.C_32K_800X_NOCOMPRESS
    PCTFREE 0 
    NOCOMPRESS 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X';

CREATE TABLE CAPSTONE.P_32K_800X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    MEASUREMENT_TIME,
    PARENT_KEY,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.C_32K_800X_RAND
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    RANDOM_VALUE,
    MEASUREMENT_VALUE;
    
CREATE TABLE CAPSTONE.P_32K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC 
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    DEVICE_NAME,
    MEASUREMENT_TIME
FROM CAPSTONE.PARENT_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    DEVICE_NAME,
    PARENT_KEY,
    MEASUREMENT_TIME;

CREATE TABLE CAPSTONE.C_32K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 
    
AS 

SELECT 
    PARENT_KEY,
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    MEASUREMENT_VALUE
FROM CAPSTONE.CHILD_TABLE_TEST
WHERE PARENT_CHILD_RATIO = '800X'
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    PARENT_KEY,
    MEASUREMENT_VALUE;




















CREATE TABLE CAPSTONE.PC_8K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_8K_10X_SORT A
    INNER JOIN CAPSTONE.C_8K_10X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_8K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_8K_50X_SORT A
    INNER JOIN CAPSTONE.C_8K_50X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_8K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_8K_200X_SORT A
    INNER JOIN CAPSTONE.C_8K_200X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.PC_8K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_8K_400X_SORT A
    INNER JOIN CAPSTONE.C_8K_400X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_8K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_8K_800X_SORT A
    INNER JOIN CAPSTONE.C_8K_800X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;









CREATE TABLE CAPSTONE.PC_16K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_16K_10X_SORT A
    INNER JOIN CAPSTONE.C_16K_10X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_16K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_16K_50X_SORT A
    INNER JOIN CAPSTONE.C_16K_50X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_16K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_16K_200X_SORT A
    INNER JOIN CAPSTONE.C_16K_200X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.PC_16K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_16K_400X_SORT A
    INNER JOIN CAPSTONE.C_16K_400X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_16K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_16K_800X_SORT A
    INNER JOIN CAPSTONE.C_16K_800X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;









CREATE TABLE CAPSTONE.PC_32K_10X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_32K_10X_SORT A
    INNER JOIN CAPSTONE.C_32K_10X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_32K_50X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_32K_50X_SORT A
    INNER JOIN CAPSTONE.C_32K_50X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_32K_200X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_32K_200X_SORT A
    INNER JOIN CAPSTONE.C_32K_200X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;

CREATE TABLE CAPSTONE.PC_32K_400X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_32K_400X_SORT A
    INNER JOIN CAPSTONE.C_32K_400X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    
CREATE TABLE CAPSTONE.PC_32K_800X_SORT
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    A.DEVICE_NAME,
    A.MEASUREMENT_TIME,
    B.PRIMARY_LOCATION,
    B.SECONDARY_LOCATION,
    B.MEASUREMENT_VALUE
FROM CAPSTONE.P_32K_800X_SORT A
    INNER JOIN CAPSTONE.C_32K_800X_SORT B
        ON A.PARENT_KEY = B.PARENT_KEY
ORDER BY
    PRIMARY_LOCATION,
    SECONDARY_LOCATION,
    DEVICE_NAME;
    















CREATE TABLE CAPSTONE.PC_8K_10X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_8K_10X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_8K_50X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_8K_50X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_8K_200X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_8K_200X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_8K_400X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_8K_400X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_8K_800X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP8K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_8K_800X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    















CREATE TABLE CAPSTONE.PC_16K_10X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_16K_10X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_16K_50X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_16K_50X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_16K_200X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_16K_200X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_16K_400X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_16K_400X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_16K_800X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP16K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_16K_800X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    















CREATE TABLE CAPSTONE.PC_32K_10X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_32K_10X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_32K_50X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_32K_50X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_32K_200X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_32K_200X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_32K_400X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K 

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_32K_400X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
CREATE TABLE CAPSTONE.PC_32K_800X_SORT_NORM
    PCTFREE 0 
    COMPRESS BASIC
    TABLESPACE CAP32K

AS

SELECT
    B.DEVICE_NAME_KEY,
    A.MEASUREMENT_TIME,
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    A.MEASUREMENT_VALUE
FROM CAPSTONE.PC_32K_800X_SORT A
    INNER JOIN CAPSTONE.DEVICE_NAME_REF B
        ON A.DEVICE_NAME = B.DEVICE_NAME
    INNER JOIN CAPSTONE.PRIMARY_LOCATION_REF C
        ON A.PRIMARY_LOCATION = C.PRIMARY_LOCATION
    INNER JOIN CAPSTONE.SECONDARY_LOCATION_REF D
        ON A.SECONDARY_LOCATION = D.SECONDARY_LOCATION
ORDER BY
    C.PRIMARY_LOCATION_KEY,
    D.SECONDARY_LOCATION_KEY,
    B.DEVICE_NAME_KEY;
    
/*
From here you should go to TABLE_SIZE_QUERY to see the results
*/