SELECT
    A.COMPRESSION,
    A.TABLE_NAME,
    A.PCT_FREE,
    A.NUM_ROWS,
    A.BLOCKS,
    B.BLOCK_SIZE,
    FLOOR(A.NUM_ROWS/NULLIF(A.BLOCKS,0)) AS ROWS_PER_BLOCK,
    A.BLOCKS * B.BLOCK_SIZE/POWER(1024,2) AS TABLE_SIZE_MB
FROM ALL_TABLES A
    INNER JOIN DBA_TABLESPACES B
        ON A.TABLESPACE_NAME = B.TABLESPACE_NAME
WHERE A.OWNER = 'CAPSTONE'
AND (A.TABLE_NAME LIKE 'P_%'
OR A.TABLE_NAME LIKE 'C_%')
AND A.TABLE_NAME NOT IN ('PARENT_TABLE_TEST','CHILD_TABLE_TEST','COMPRESSION_TYPES')
ORDER BY
    TABLE_SIZE_MB DESC NULLS LAST;
    
SELECT
    'DROP TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ';' AS DROP_TABLE_STATEMENT
FROM ALL_TABLES A
WHERE A.TABLE_NAME LIKE 'PARENT_TABLE%'
OR A.TABLE_NAME LIKE 'CHILD_TABLE%';

WITH TABLE_ORDERING AS

(
SELECT
    *
FROM CAPSTONE.CHILD_TABLE_TEST
ORDER BY
    MEASUREMENT_VALUE, PARENT_KEY, SECONDARY_LOCATION, PRIMARY_LOCATION
--    PRIMARY_LOCATION,SECONDARY_LOCATION,PARENT_KEY,MEASUREMENT_VALUE
)

SELECT
    COUNT(DISTINCT MEASUREMENT_VALUE) AS DIST_MEAS,
    COUNT(DISTINCT MEASUREMENT_VALUE||PARENT_KEY) AS DIST_MEAS_KEY,
    COUNT(DISTINCT PRIMARY_LOCATION||SECONDARY_LOCATION) AS DIST_PRIM_SECOND,
    COUNT(DISTINCT PRIMARY_LOCATION||SECONDARY_LOCATION||PARENT_KEY) AS DIST_PRIM_SEC_KEY,
    COUNT(DISTINCT PARENT_KEY||SECONDARY_LOCATION||PRIMARY_LOCATION) AS DIST_KEY_SEC_PRIM
FROM TABLE_ORDERING
WHERE ROWNUM <= 400;

SELECT * FROM ALL_TAB_COLS WHERE TABLE_NAME = 'CHILD_TABLE_SORT';