/*
Table size query.  Also categorizes the experiment splits for easy graphing in Excel
*/

SELECT
    A.COMPRESSION,
    CASE
        WHEN TABLE_NAME LIKE 'PC%' THEN 'PARENT_CHILD'
        WHEN TABLE_NAME LIKE 'P%' THEN 'PARENT'
        WHEN TABLE_NAME LIKE 'C%' THEN 'CHILD'
    END AS TABLE_TYPE,
    CASE
        WHEN TABLE_NAME LIKE 'PC%' THEN 'COMBINED'
        ELSE 'SEPERATE'
    END AS COMBINED_OR_SEPERATE,
    CASE
        WHEN TABLE_NAME LIKE '%10X%' THEN '10X'
        WHEN TABLE_NAME LIKE '%50X%' THEN '50X'
        WHEN TABLE_NAME LIKE '%200X%' THEN '200X'
        WHEN TABLE_NAME LIKE '%400X%' THEN '400X'
        WHEN TABLE_NAME LIKE '%800X%' THEN '800X'
    END AS PARENT_CHILD_RATIO,
    CASE
        WHEN TABLE_NAME LIKE '%SORT%' THEN 'SORT'
        WHEN TABLE_NAME LIKE '%RAND%' THEN 'RANDOM'
        ELSE 'NO_COMPRESS'
    END AS SORT_OR_RANDOM,
    CASE
        WHEN TABLE_NAME LIKE '%NORM%' THEN 'NORMALIZED'
        ELSE 'DENORMALIZED'
    END AS NORM_DENORM,
    A.TABLE_NAME,
    A.PCT_FREE,
    A.NUM_ROWS,
    A.BLOCKS,
    B.BLOCK_SIZE/1024 || 'K' AS BLOCK_SIZE,
    FLOOR(A.NUM_ROWS/NULLIF(A.BLOCKS,0)) AS ROWS_PER_BLOCK,
    A.BLOCKS * B.BLOCK_SIZE/POWER(1024,2) AS TABLE_SIZE_MB
FROM ALL_TABLES A
    INNER JOIN DBA_TABLESPACES B
        ON A.TABLESPACE_NAME = B.TABLESPACE_NAME
WHERE A.OWNER = 'CAPSTONE'
AND (A.TABLE_NAME LIKE 'P_%'
OR A.TABLE_NAME LIKE 'C_%')
AND A.TABLE_NAME NOT IN ('PARENT_TABLE_TEST','CHILD_TABLE_TEST','COMPRESSION_TYPES','PRIMARY_LOCATION_REF','SECONDARY_LOCATION_REF','DEVICE_NAME_REF')
ORDER BY
    TABLE_SIZE_MB DESC NULLS LAST,
    TABLE_NAME;
    
/*
If you need to delete all the tables you just created.
*/
SELECT
    'DROP TABLE ' || A.OWNER || '.' || A.TABLE_NAME || ';' AS DROP_TABLE_STATEMENT
FROM ALL_TABLES A
WHERE A.OWNER = 'CAPSTONE'
AND (A.TABLE_NAME LIKE 'P_%'
OR A.TABLE_NAME LIKE 'C_%')
AND A.TABLE_NAME NOT IN ('PARENT_TABLE_TEST','CHILD_TABLE_TEST','COMPRESSION_TYPES','PRIMARY_LOCATION_REF','SECONDARY_LOCATION_REF','DEVICE_NAME_REF');


